apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: odms.ibm.odm.com
spec:
  group: ibm.odm.com
  names:
    kind: Odm
    listKind: OdmList
    plural: odms
    singular: odm
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
